version: 2.1
jobs:
  build:
    working_directory: ~/chameleon
    docker:
      - image: circleci/node:current-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm config set prefix '~/.npm-global'
            npm run setup
      - run: # run tests
          name: Test
          command: npm test
      - run: # run coverage report
          name: Code Coverage
          command: |
            npx codecov
      - run:
          name: Build
          command: |
            npm run build
